feat(rating-menu): implement `getRenderState` and `getWidgetRenderState`
algolia/instantsearch.js pull request #4548
Opened 2020-10-27 10:26 UTC by yannickcr

This implements the `getRenderState` and `getWidgetRenderState` widget lifecycle hooks in `ratingMenu`.

2020-10-27 12:14 UTC, Haroenv commented on src/connectors/rating-menu/__tests__/connectRatingMenu-test.js
> +      const rangeWidget = createRatingMenu({
you have `rangeWidget` instead of ratingWidget a few times

2020-10-30 10:50 UTC, eunjae-lee approved these changes
looks good to me

2020-10-30 12:31 UTC, Haroenv approved these changes
looks good! (technically a breaking change, but not on public api so it's alright for me)

2020-10-30 12:32 UTC, Haroenv requested changes
the breaking change you did requires you update the rating menu tests: https://app.circleci.com/pipelines/github/algolia/instantsearch.js/4950/workflows/50783eb6-0218-4c6b-915d-745f888967c5/jobs/21823

2020-10-30 13:55 UTC, yannickcr commented
Fixed the tests, and yes since it is not a public API this change is fine IMHO :slightly_smiling_face:

2020-11-04 17:37 UTC, devdreamsolution approved these changes

2020-11-09 17:40 UTC, Haroenv approved these changes
Good enough for now, but the getWidgetRenderState & getWidgetState tests could be split up

2020-11-09 18:00 UTC, merged