chore(test): updates jest
algolia/instantsearch.js pull request #4746
Opened 2021-04-22 12:55 UTC by Haroenv

**Summary**

also avoids some of the extra `console.warn` calls that we weren't testing, since now that takes up a lot of space in the output

**Result**

1. the updates from the latest jest versions
2. less annoying warn messages in the console (wip, there are still more to remove before merging this PR)

2021-04-28 13:02 UTC, Haroenv commented
todo widgetSnapshotSerializer:

```js
export const widgetSnapshotSerializer: jest.SnapshotSerializerPlugin = {
  serialize(widget: Widget | Index, { indent }, indentation) {
    const keys = {
      $$widgetType: widget.$$widgetType,
      attribute: getAttribute(widget),
    };

    const widgetName = `Widget(${widget.$$type || 'unknown'})`;

    const content = Object.entries(keys)
      .filter(([_key, value]) => value)
      .map(([key, value]) => `${indentation}${indent}${key}: ${value}`)
      .join('\n');

    if (content) {
      return `${widgetName} {
${content}
${indentation}}`;
    }

    return widgetName;
  },
  test(value) {
    return Boolean(value?.$$type);
  },
};
```

2021-04-29 09:31 UTC, eunjae-lee requested changes

2021-04-29 09:31 UTC, eunjae-lee commented on src/widgets/answers/__tests__/answers-test.ts
> +  runAllMicroTasks,
The names are a bit confusing.

Refer to `test/utils/wait.ts`

2021-04-29 13:06 UTC, eunjae-lee approved these changes

2021-05-03 12:59 UTC, merged