chore: release v4.38.0
algolia/instantsearch.js pull request #5003
Opened 2022-01-28 10:31 UTC by dhayab

This pull request prepares the following release:
| Repository | Branch | Update | Change |
|---|---|---|---|
| [instantsearch.js](https://github.com/algolia/instantsearch.js) | releases/v4.38.0 | minor | [`4.37.3` → `4.38.0`](https://github.com/algolia/instantsearch.js/compare/v4.37.3...releases/v4.38.0) |

### Release Summary
This is going to be published with the following command:

```yarn publish --no-git-tag-version --non-interactive --tag latest```

### Merging Instructions
When merging this pull request, you need to **Squash and merge** and make sure that the title starts with `chore: release v4.38.0`.
<details>
<summary>See details</summary>

After that, a commit `chore: release v4.38.0` will be added and you or your CI can run `shipjs trigger` to trigger the release based on the commit.
![Squash and merge](https://raw.githubusercontent.com/algolia/shipjs/v0.21.0/assets/squash-and-merge.png)
</details>

---

_This pull request is automatically generated by [Ship.js](https://github.com/algolia/shipjs)_.

2022-01-28 10:36 UTC, sarahdayan approved these changes

2022-01-28 10:41 UTC, Haroenv requested changes
let's release this Monday instead

2022-01-31 13:18 UTC, Haroenv approved these changes

2022-01-31 13:27 UTC, francoischalifour approved these changes

2022-01-31 13:27 UTC, merged