chore(instantsearch.css): remove unused class
algolia/instantsearch.js pull request #5202
Opened 2022-12-16 15:50 UTC by sarahdayan

## Summary

This removes the `.ais-ToggleRefinement-count` CSS class from our themes and examples. This class was removed a while ago from the `toggleRefinement` markup but somehow wasn't removed from the specs and themes.

This is technically a breaking change to remove those from the themes because users could have manually added an element with `class="ais-ToggleRefinement-count"` and rely on the styles. However, since `instantsearch.css` already received a breaking change and hasn't been released, this should be fine to embark this change with it.

Related: https://github.com/algolia/instantsearch-specs/issues/93

2022-12-16 15:56 UTC, aymeric-giraudet approved these changes

2022-12-16 15:57 UTC, FabienMotte approved these changes

2022-12-18 15:26 UTC, Haroenv requested changes
Vue InstantSearch has a count on toggleRefinement still

2022-12-19 12:40 UTC, sarahdayan commented
Ah, damn! Closing this then.

2022-12-19 12:40 UTC, closed without merging